### ISSUE TITLE
Missing submissions

### ISSUE THREAD

**Issue by alexpanter** [DIKU-EDU/staffeli#19]
When I use the command `staffeli --metadata fetch subs/<assignment>` I get a lot of empty folders named by KUID_<int>, but no submissions.

**Comment by oleks** [comment]
> On 11 Feb 2017, at 12:32, Alexander Christensen <notifications@github.com> wrote:
> 
> When I use the command staffeli --metadata fetch subs/<assignment> I get a lot of empty folder named by KUID_, but no submissions.
> 

That's the point of --metadata ;-) try without the flag.

**Comment by alexpanter** [comment]
okay lol. thanks :+1:
