### ISSUE TITLE
Accept files for input the feedback messages when grading

### ISSUE THREAD

**Issue by frenzeldk** [DIKU-EDU/staffeli#21]

**Comment by nqpz** [comment]
You can already do this.  However, Canvas currently seems to have a limit to how much feedback file data you can upload through the API.  Refer to our ongoing discussion with the Canvas developers at https://community.canvaslms.com/message/53941.

**Comment by oleks** [comment]
The feature request here is to be able to throw in a file (.txt) _as_ the message.

**Comment by nqpz** [comment]
Aha!  Easy.

**Comment by truls** [comment]
This issue is resolved? I have been giving files as feedback messages so far in IPS

**Comment by nqpz** [comment]
Yes.
