### ISSUE TITLE
Treating paths as strings is a bad assumption.

### ISSUE THREAD

**Issue by frenzeldk** [DIKU-EDU/staffeli#22]
Currently Staffeli assumes specific string representations of paths. This leads to an incompatibility with e.g. PowerShell as it prepends `.\` to all relative paths.

**Comment by oleks** [comment]
I'm not sure what you are suggesting in place of Python strings?

**Comment by athas** [comment]
Paths are logically byte strings.

-- 
\  Troels
/\ Henriksen

**Comment by oleks** [comment]
Closing this as I don't understand what the suggested alternative is to using `os.path`-functions.
