### ISSUE TITLE
Staffeli should not silently use the message 'See attached files' if I pass neither -m nor -f when correcting

### ISSUE THREAD

**Issue by athas** [DIKU-EDU/staffeli#39]
Instead it should not upload a comment at all, or (if required), the comment 'No further comment' or similar.

**Comment by sshine** [comment]
I believe this is a product of Oleks' way of grading: Upload a file with feedback and point to this in the comment section. So Oleks did not assume that you would grade without any of -m, -f or attachment.

With your case in mind of passing a resubmission without further comment, the pragmatic choice would be to not require -m, -f or an attachment, and at the most print a comment about not having left a comment.

I'll make "See attached file(s)." a default comment only if there actually is an attachment.

At the same time I'll make -m and -f mutually exclusive.
