### ISSUE TITLE
Python vs. Golang vs. Rust — I think we're sticking with Python

### ISSUE THREAD

**Issue by oleks** [DIKU-EDU/staffeli#46]
Staffeli is written in Python 3 for the following reason: "Python 3, is deemed[1] a popular, modern, cross-platform language. Python 3 is the primary choice for every part of Staffeli. Cross-platform Python 3 code SHOULD be preferred over non-cross-platform code. For instance, when handling file-system paths." — [DESIGN.md](https://github.com/DIKU-EDU/staffeli/blob/master/DESIGN.md).

I have on occasion discussed rewriting Staffeli in Golang or Rust.

The Python implementation has grown to use [mypy](http://mypy-lang.org/) for static type checking, [flake8](http://flake8.pycqa.org/en/latest/) for style conformity, as well as [pytest](https://docs.pytest.org/en/latest/) and [hypothesis](https://hypothesis.readthedocs.io/en/latest/) for (quick-check style) testing.

I believe that Staffeli should move on to have a simple, safe core (statically typed and tested quick-check style), but allow people to hack around it in the interest of deadlines, without being subject to both a pedantic type-checker and having to write thorough tests. (For instance, you might implement a Staffeli extension, write a simple test for it, send it through a continuous integration pipeline, and go on to the real work. Then, you can come back later, when you have more time, type your code and write more exhaustive tests.)

The benefit of Golang or Rust is that their type-systems are much more mature than mypy. The benefit of Python is that dynamic types are nice for when you want to just hack around Staffeli. That however, could be achieved with a mere Python language binding around a Golang/Rust core.

The quick-check sittuation is also much nicer in [Python](https://hypothesis.readthedocs.io/en/latest/) and [Rust](https://github.com/BurntSushi/quickcheck) than it is in [Golang](https://github.com/leanovate/gopter), but Rust IMO is harder for newcomers to learn than Golang.

Also mentioning @kfl @Athas @sshine.

__
[1]: By @oleks, @nqpz, @Orkeren

**Comment by athas** [comment]
Go has a ridiculous 70s-style Fischer Price type system.  If the desire for a good type system is the motivation for change, then Go is a bad choice (but it might be a good choice for other reasons).

Rust's domain is not at all the kind of problem that Staffeli is trying to solve.

I could buy the desire to rewrite Staffeli in a safer language, but then why not pick F# or something else that we both teach at DIKU, and which actually has a good type system?

**Comment by oleks** [comment]
I'm OK with F#.

**Comment by oleks** [comment]
Also, "Staffeli SHOULD be easy to maintain for the foreseeable future." — [DESIGN.md](https://github.com/DIKU-EDU/staffeli/blob/master/DESIGN.md). This was another reason why we chose Python 3.

I think at this point we also have to think beyond DIKU. Other CS institutions may be less fortunate and not teach functional programming in the very first year. That speaks in favor of sticking with Python and mypy.

**Comment by oleks** [comment]
Python it is.
