### ISSUE TITLE
Moving

### ISSUE THREAD

**Issue by oleks** [DIKU-EDU/staffeli#47]
I am transferring to University in Oslo, but I intend to continue contributing/maintaining Staffeli, not least because they also use Canvas at UiO. Staffeli is mostly a DIKU project, so maybe it is best suited under the flag of the diku-dk organization. If you agree, how about a team like "eduhackers" for those involved in Staffeli development under diku-dk?

**Comment by athas** [comment]
I find the colour of the bikeshed pleasing.

-- 
\  Troels
/\ Henriksen
