### ISSUE TITLE
feedback.py is broken

### ISSUE THREAD

**Issue by oleks** [DIKU-EDU/staffeli#8]
[Uploading via URL](https://canvas.instructure.com/doc/api/file.file_uploads.html#method.file_uploads.url) imposes some a limit (~50MB) on the amount of data that can be uploaded wrt. submissions. See also our [Canvas Community post](https://community.canvaslms.com/thread/13648).

I suppose our best option is to once again try [uploading via POST](https://canvas.instructure.com/doc/api/file.file_uploads.html#method.file_uploads.post). Last we tried, Canvas didn't yield all the fields necessary for upload to their S3 store.

**Comment by kfl** [comment]
This might be a limitation in the file-transfer service, sorry.

**Comment by oleks** [comment]
I don't think so?

**Comment by kfl** [comment]
There is _some_ limit on file size in file-transfer (if you still use that), and 50MB sounds about right.
